#!/bin/bash
files_changed=$(git diff --name-only)
file_count=0

for file_changed in $files_changed
do
	git add "$file_changed"
	file_count=$[file_count + 1]
	echo "Add file $file_changed to the commit"
done

if [ $file_count -ge 1 ]
then
	if [ -n "$1" ]
	then
		git commit -m "$1"
		echo "$file_count files committed"
	else
		git commit --fixup=HEAD -m 'fixup'
		echo "$file_count files fixup commited"
	fi
else
	echo "Nothing to commit."
fi


