#!/bin/bash

# Do not allow to commit on master
git_branch=$(git rev-parse --abbrev-ref HEAD)
if [[ $git_branch = 'master' ]]
then
	echo "Commit on master is not allowed!!!"
	exit 3
fi

files_changed=$(git diff --name-only)
file_count=0

for file_changed in $files_changed
do
	git add "$file_changed"
	file_count=$[file_count + 1]
	echo "Add file $file_changed to the commit"
done

if [ $file_count -ge 1 ]
then
	if [ -n "$1" ]
	then
		git commit -m "$1"
		echo "$file_count files committed"
	else
		git commit --fixup=HEAD -m 'fixup'
		echo "$file_count files fixup commited"
	fi
else
	echo "Nothing to commit."
fi


